services:
  nginx:
    image: nginx-42
    ports:
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./certificates/nginx:/etc/nginx/ssl:ro
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  mariadb:
    env_file:
      - ./env/.env_mariadb
    image: mariadb-42
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - inception_network
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -u\"$${MYSQL_USER}\" --password=\"$${MYSQL_PASSWORD}\""]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  adminer:
    image: adminer-42
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - inception_network
    env_file:
      - ./env/.env_adminer
    healthcheck:
      test: ["CMD-SHELL", "php", "-l", "/var/www/html/index.php"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  wordpress:
    image: wordpress-42
    env_file:
      - ./env/.env_wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    image: redis-42
    env_file:
      - ./env/.env_redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis_data:/data:rw
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  ftp-server:
    image: ftp-server-42
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    env_file:
      - ./env/.env_ftp_server
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "ftp://localhost:21"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

volumes:
  mariadb_data:
    external: true
  wordpress_data:
    external: true
  redis_data:
    external: true

networks:
  inception_network:
    driver: overlay
    external: true
