services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./certificates/nginx:/etc/nginx/ssl:ro
    restart: always
    networks:
      - network
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  mariadb:
    container_name: mariadb
    env_file:
      - ./env/.env_mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - network
    ports:
      - "3306:3306"
    restart: always
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - network
    restart: always
    env_file:
      - ./env/.env_adminer
    healthcheck:
      test: ["CMD", "php", "-l", "/var/www/html/index.php"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    restart: always
    env_file:
      - ./env/.env_wordpress
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - network
    healthcheck:
      test: ["CMD", "/bin/bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    restart: always
    env_file:
      - ./env/.env_redis
    volumes:
      - redis_data:/data:rw
    networks:
      - network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp_server
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - network
    restart: always
    env_file:
      - ./env/.env_ftp_server

volumes:
  mariadb_data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/mysql
  wordpress_data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/wordpress
  redis_data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/redis

networks:
  network:
    driver: bridge
